CREATE TABLE `workers` (
	`id` text PRIMARY KEY NOT NULL,
	`entry_date` text NOT NULL,
	`full_name` text NOT NULL,
	`identity_number` text NOT NULL,
	`birth_date` text NOT NULL,
	`nationality` text NOT NULL,
	`marital_status` text NOT NULL,
	`education_level` text NOT NULL,
	`professional_title` text DEFAULT '' NOT NULL,
	`address` text NOT NULL,
	`commune` text NOT NULL,
	`region` text NOT NULL,
	`mobile` text NOT NULL,
	`email` text NOT NULL,
	`family_dependents` integer DEFAULT 0 NOT NULL,
	`disability_or_invalidity` text NOT NULL,
	`role` text NOT NULL,
	`work_site` text NOT NULL,
	`contract_term` text NOT NULL,
	`agreed_salary` integer NOT NULL,
	`afp` text NOT NULL,
	`health` text NOT NULL,
	`isapre_plan` text DEFAULT '' NOT NULL,
	`bank` text NOT NULL,
	`account_type` text NOT NULL,
	`account_number` text NOT NULL,
	`requires_advance` integer DEFAULT false NOT NULL,
	`emergency_name` text NOT NULL,
	`emergency_relationship` text NOT NULL,
	`emergency_mobile` text NOT NULL,
	`source` text DEFAULT 'Individual' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `workers_identity_number_unique` ON `workers` (`identity_number`);