import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const processes = sqliteTable("processes", {
  id: text("id").primaryKey(),
  type: text("type").notNull(),
  rut: text("rut").notNull(),
  personName: text("person_name").notNull(),
  company: text("company").notNull(),
  costCenter: text("cost_center").notNull(),
  role: text("role").notNull(),
  workday: text("workday").notNull(),
  startDate: text("start_date").notNull(),
  status: text("status").notNull().default("Iniciado"),
  stage: text("stage").notNull().default("Revisión de RRHH"),
  requiredDocuments: text("required_documents").notNull().default("[]"),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const auditEvents = sqliteTable("audit_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userName: text("user_name").notNull(),
  module: text("module").notNull(),
  action: text("action").notNull(),
  recordId: text("record_id").notNull(),
  detail: text("detail").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const workers = sqliteTable("workers", {
  id: text("id").primaryKey(),
  entryDate: text("entry_date").notNull(),
  fullName: text("full_name").notNull(),
  identityNumber: text("identity_number").notNull().unique(),
  birthDate: text("birth_date").notNull(),
  nationality: text("nationality").notNull(),
  gender: text("gender").notNull().default("No informado"),
  maritalStatus: text("marital_status").notNull(),
  educationLevel: text("education_level").notNull(),
  professionalTitle: text("professional_title").notNull().default(""),
  address: text("address").notNull(),
  commune: text("commune").notNull(),
  region: text("region").notNull(),
  mobile: text("mobile").notNull(),
  email: text("email").notNull(),
  familyDependents: integer("family_dependents").notNull().default(0),
  disabilityOrInvalidity: text("disability_or_invalidity").notNull(),
  role: text("role").notNull(),
  workSite: text("work_site").notNull(),
  contractTerm: text("contract_term").notNull(),
  agreedSalary: integer("agreed_salary").notNull(),
  afp: text("afp").notNull(),
  health: text("health").notNull(),
  isaprePlan: text("isapre_plan").notNull().default(""),
  bank: text("bank").notNull(),
  accountType: text("account_type").notNull(),
  accountNumber: text("account_number").notNull(),
  requiresAdvance: integer("requires_advance", { mode: "boolean" }).notNull().default(false),
  emergencyName: text("emergency_name").notNull(),
  emergencyRelationship: text("emergency_relationship").notNull(),
  emergencyMobile: text("emergency_mobile").notNull(),
  source: text("source").notNull().default("Individual"),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const workerRecords = sqliteTable("worker_records", {
  id: text("id").primaryKey(),
  workerRut: text("worker_rut").notNull(),
  category: text("category").notNull(),
  subtype: text("subtype").notNull(),
  title: text("title").notNull(),
  issueDate: text("issue_date").notNull().default(""),
  expiryDate: text("expiry_date").notNull().default(""),
  status: text("status").notNull().default("Vigente"),
  detail: text("detail").notNull().default(""),
  metadata: text("metadata").notNull().default("{}"),
  fileName: text("file_name").notNull().default(""),
  fileKey: text("file_key").notNull().default(""),
  contentType: text("content_type").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});

export const medicalLeaves = sqliteTable("medical_leaves", {
  id: text("id").primaryKey(),
  workerRut: text("worker_rut").notNull(),
  workerName: text("worker_name").notNull(),
  costCenter: text("cost_center").notNull(),
  dateFrom: text("date_from").notNull(),
  dateTo: text("date_to").notNull(),
  days: integer("days").notNull(),
  folio: text("folio").notNull(),
  specialty: text("specialty").notNull().default(""),
  status: text("status").notNull().default("Registrada"),
  fileName: text("file_name").notNull().default(""),
  fileKey: text("file_key").notNull().default(""),
  contentType: text("content_type").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
